name: Quality Checks

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unit tests
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x
      - run: yarn
      - run: yarn test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cypress
        uses: cypress-io/github-action@v5
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lints
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x
      - run: yarn
      - run: yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lints
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x
      - run: yarn
      - run: yarn build

