name: Quality Checks
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  #  test:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v3
  #      - name: Unit tests
  #        uses: actions/setup-node@v3
  #        with:
  #          node-version: 18.x.x
  #      - run: yarn
  #      - run: yarn test
  #      - name: cypress
  #        uses: cypress-io/github-action@v5
  #        with:
  #          start: npm run e2e
  #          command: npm run cy-ci
  #      - name: SonarCloud Scan
  #        uses: SonarSource/sonarcloud-github-action@master
  #        env:
  #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #      - uses: actions/upload-artifact@v3
  #        with:
  #          name: cypress-videos
  #          path: cypress/videos
  #          if-no-files-found: ignore
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unit tests
        uses: actions/setup-node@v3
        with:
          node-version: 20.x.x
      - run: yarn
        # - name: Map hosts
        #   run: yarn build
      - name: cypress
        uses: cypress-io/github-action@v5
        with:
          start: npm run e2e
          command: npm run cy-ci
            # - name: SonarCloud Scan
            #   uses: SonarSource/sonarcloud-github-action@master
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

            #  lint:
            #    runs-on: ubuntu-latest
            #    steps:
            #      - uses: actions/checkout@v3
            #      - name: Lints
            #        uses: actions/setup-node@v3
            #        with:
            #          node-version: 18.x.x
            #      - run: yarn
            #      - run: yarn lint
            #  build:
            #    runs-on: ubuntu-latest
            #    steps:
            #      - uses: actions/checkout@v3
            #      - name: Lints
            #        uses: actions/setup-node@v3
            #        with:
            #          node-version: 18.x.x
            #      - run: yarn
            #      - run: yarn build
            #
